INSERT INTO humor (blurb, author, topic) 
VALUES ("Without requirements or design, programming is the art of adding bugs to an empty text file.", "Louis Srygley", "Inspiration"),
("Before software can be reusable it first has to be usable.", "Ralph Johnson", "Inspiration"),
("There are two ways to write error-free programs; only the third one works.", "Alan J. Perlis", "Inspiration"),
("It’s not a bug – it’s an undocumented feature.", "Anonymous", "Inspiration"),
("One man’s crappy software is another man’s full-time job.", "Jessica Gaston", "Inspiration"),
("A good programmer is someone who always looks both ways before crossing a one-way street.", "Doug Linder", "Inspiration"),
("Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.", "Martin Golding", "Inspiration"),
("Deleted code is debugged code.", "Jeff Sickel", "Inspiration"),
("Software undergoes beta testing shortly before it’s released. Beta is Latin for “still doesn’t work.", "Anonymous", "Inspiration"),
("It’s a curious thing about our industry: not only do we not learn from our mistakes, but we also don’t learn from our successes.", "Ralph Johnson", "Inspiration"),
("The cheapest, fastest, and most reliable components are those that aren’t there.", "Ralph Johnson", "Inspiration"),
("Before software can be reusable it first has to be usable.", "Gordon Bell", "Inspiration"),
("The best performance improvement is the transition from the nonworking state to the working state.", "J. Osterhout", "Inspiration"),
("The trouble with programmers is that you can never tell what a programmer is doing until it’s too late.", "Seymour Cray", "Inspiration"),
("Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.", "Mosher’s Law of Software Engineering", "Inspiration"),
